### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/insim.rs#2]
@Dygear I've been toying with your idea from twitter and trying to take into account what a general purpose insim client might need to look like, so that we could build stuff like PRISM in rust. I'm definitely still at the tinkering phase and I was hoping you would have some input (as I suspect you're further along with rust than I am).

I kind of like the macro style that that projects [serenity](https://github.com/serenity-rs/serenity#example-bot) and [rocket](https://rocket.rs/) use. I just don't know if that's a good or bad idea.

Or we could go for a callback per packet type (which seems horrible given the number of packets in Insim).

Or there's just the receive everything to a single handler func/lambda/whatever and let upstream projects (like PRISM) handle dispatching.

Any thoughts? :)

**Comment by Dygear** [comment]
I was thinking more along the lines of client_connected callback when someone connects to the server like [AMX Mod's native functions](https://www.amxmodx.org/api/amxmodx/__functions). Basically the same documentation too.

**Comment by theangryangel** [comment]
I shall investigate further <3

**Comment by Dygear** [comment]
https://www.lfs.net/forum/post/1969418#post1969418
