### ISSUE TITLE
insim: relay websocket support

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/insim.rs#80]
I'm chalking this down for initial release as I really want to validate that it's possible to support further underlying IO transports, without needing a huge breaking change.

The initial release is aimed to be the path to stabilisation.

Whilst I've technically proven this with UDP and TCP support, and Mock IO support, I'd really like something that fundamentally works differently to make sure that there's not something lurking that I've not thought of.

**Comment by theangryangel** [comment]
Have raised #81.

LFS World websocket relay seems to be dead, or tungstenite is incompatible. I haven't investigated very far, based on https://www.lfs.net/forum/post/2042576#post2042576.

In principle it works, which is primarily what I wanted to see (i.e. can we make an arbitrary ClientTransport - the answer is yes!).

**Comment by mkapal** [comment]
> LFS World websocket relay seems to be dead, or tungstenite is incompatible. I haven't investigated very far, based on https://www.lfs.net/forum/post/2042576#post2042576.

The websocket LFS relay service has been back up again for a couple of weeks, so you can test it.

**Comment by theangryangel** [comment]
Thanks for the heads up Martin <3 I shall have to find some time to play over the weekend :D

**Comment by theangryangel** [comment]
Implemented under #95.

Turns out LFSW Relay requires the `Origin` header. Which Tungstenite (and most non-web browser libraries seem to not set).
